fix: add missing alternate_categories argument to check_taxonomy_hierarchy
ERROR: check_taxonomy_hierarchy() missing 1 required positional argument
FIX: Added row[3] (alternate_categories) as 3rd argument

Function signature:
check_taxonomy_hierarchy(category_tags, overture_category, alternate_categories, config)